Server:
  port: 8082

spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message: Welcome to Daily Code Buffer!! Server is Up Dev Server!!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
---
spring:
  profiles: Test
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message: Welcome to Daily Code Buffer!! Server is Up Test Server!!!

---

spring:
  profiles: prod
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message: Welcome to Daily Code Buffer!! Server is Up Production Server!!!